### ISSUE TITLE
Not Found Route

### ISSUE THREAD

**Issue by elithrar** [lrdiv/ember-soundcloud#16]
Although it's unlikely to hit a 404 (via the app itself) there isn't a mechanism to catch these. Adding a `not-found` catch-all route to the bottom of your router with a `not-found` Route and template would resolve this.

e.g.

``` js
Router.map ->
  @route 'index', { path: '/' }
  @route 'artist', { path: '/:artist' }, ->
    @route 'playlist', { path: '/:playlist' }
  // Add this
  @route 'not-found', { path: '*wildcard' }
```

**Comment by lrdiv** [comment]
@elithrar Thanks, I'll implement this as soon as I get a chance!
