### ISSUE TITLE
Ember Cli with Broccoli emblem compiler

### ISSUE THREAD

**Issue by Mannaio** [lrdiv/ember-soundcloud#2]
I am trying to set up this repository locally and i have come across to this issue with broccoli-emblem-compiler. See the image: http://i.stack.imgur.com/J7Gu6.jpg

![broccoli-emblem-compiler](https://cloud.githubusercontent.com/assets/1617078/6339213/9ba65daa-bbb4-11e4-979e-ea086faab5ec.jpg)

From my understanding the broccoli-emblem-compiler is not able to compile my emblem templates and i don't know how i can figure it out.

What can i do now to sort this out? What's really the problem?

I have also posted the issue here explaining step by step:  http://stackoverflow.com/questions/28662049/ember-cli-not-compiling-with-broccoli-emblem-compiler

**Comment by lrdiv** [comment]
@Mannaio If you pull the most recent update, remove your node_modules directory, then run:

`npm cache clean && npm install` 

this issue should be resolved.
